Workflow fix
aws/aws-xray-sdk-dotnet pull request #183
Opened 2021-02-18 22:04 UTC by srprash

*Description of changes:*
Noticed the workflow failure on [this](https://github.com/aws/aws-xray-sdk-dotnet/actions/runs/579560564) run because there was an `-` before `uses` key. Removing the `-` 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-18 22:19 UTC, lupengamzn requested changes
The build failure on windows os seems like a similar issue discussed [here](https://github.com/actions/virtual-environments/issues/1090#issuecomment-748452120). Can you address it following the suggestions mentioned in the thread?

2021-02-18 22:32 UTC, srprash commented
Restore seems be looking into the local package cache by default. I think it will be good to define the package source as nuget.org as is done in [this PR](https://github.com/aws/aws-xray-sdk-dotnet/pull/180/files#diff-aab1525a907935fd3480702f8d2e6f430e949811da0b53c52f794cb96e94ed81) by adding a `Nuget.config` file. This way restore will download packages from nuget.org where it should find everything.

2021-11-10 23:50 UTC, willarmiros commented
@srprash is this PR still relevant? If not can we close it out?

2022-03-28 15:26 UTC, srprash commented
Closing the PR as it is not needed anymore.

2022-03-28 15:26 UTC, closed without merging